### PR TITLE
update to 3.1.0

### LINKED ISSUE #9: Update to 3.1.0
review release notes:
https://github.com/omeka/omeka-s/releases/tag/v3.1.0

Document upgrade steps:
https://omeka.org/s/docs/user-manual/install/

Perform the upgrade

Push to GitHub and create pull request

### PR DESCRIPTION
**Pull request by crowesn**
Resolves #9

### CODE REVIEW

**Comment by hortongn** [comment]
Everything is working on the upgraded version?  Themes and modules work?

**Comment by crowesn** [comment]
@lisa3711

**Comment by crowesn** [comment]
Hey @lisa3711 are we ready to go with this?

**Comment by lisa3711** [comment]
Sure!

From: Sean Crowe ***@***.***>
Reply-To: uclibs/omeka-s ***@***.***>
Date: Tuesday, September 14, 2021 at 1:54 PM
To: uclibs/omeka-s ***@***.***>
Cc: "Haitz, Lisa (haitzlm)" ***@***.***>, Mention ***@***.***>
Subject: Re: [uclibs/omeka-s] update to 3.1.0 (#15)


Hey @lisa3711<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flisa3711&data=04%7C01%7Chaitzlm%40ucmail.uc.edu%7Cfd01c861b0864f80823808d977a8abc8%7Cf5222e6c5fc648eb8f0373db18203b63%7C1%7C0%7C637672388586803774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9BlKzMveQfWCsCzRt58zIIFeLVYiSCBFAJXkuvy5msw%3D&reserved=0> are we ready to go with this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fuclibs%2Fomeka-s%2Fpull%2F15%23issuecomment-919383297&data=04%7C01%7Chaitzlm%40ucmail.uc.edu%7Cfd01c861b0864f80823808d977a8abc8%7Cf5222e6c5fc648eb8f0373db18203b63%7C1%7C0%7C637672388586803774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4tiZ%2Bqxq9S8G58aTBfHo7SoVHYBRqRrPQhFhjm8U894%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAADYQVTIBEZUI3R4YOTK3GTUB6D4RANCNFSM5DX3NEUQ&data=04%7C01%7Chaitzlm%40ucmail.uc.edu%7Cfd01c861b0864f80823808d977a8abc8%7Cf5222e6c5fc648eb8f0373db18203b63%7C1%7C0%7C637672388586813726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qDLrC4Naof29kivh3BUiAMjKOiWBeRO8If6MgapPJDY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Chaitzlm%40ucmail.uc.edu%7Cfd01c861b0864f80823808d977a8abc8%7Cf5222e6c5fc648eb8f0373db18203b63%7C1%7C0%7C637672388586813726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T9AHsKBIRtq1LOGJRWFtkPbrK64cAKTFvFi6OY9kSvQ%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Chaitzlm%40ucmail.uc.edu%7Cfd01c861b0864f80823808d977a8abc8%7Cf5222e6c5fc648eb8f0373db18203b63%7C1%7C0%7C637672388586823688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=80%2BgcarRqOWYHHcOJK5rCgYeoPYXdm6iYPlSrTwpKyk%3D&reserved=0>.

**Review by hortongn — APPROVED** [review]
@lisa3711 confirmed all is well with the upgrade.  So I'm merging this.

**Pull request merged**
